### PR TITLE
Fix php8 compat

### PR DESCRIPTION
**Pull request by rabauss**

### CODE REVIEW

**Comment by rabauss** [comment]
Are there any wishes to merge this PR?

**Comment by frontendschlampe** [comment]
shure ... we'll check it next week ... sorry for delay

**Comment by rabauss** [comment]
hello?

**Review by dmolineus — APPROVED** [review]
Thanks @rabauss, sorry for the delay.

**Comment by dmolineus** [comment]
Released as 1.1.1.

**Pull request merged**
