### PR TITLE
Added missing page social tags fix for extractOpenGraphTitle Method

### LINKED ISSUE #28: PageExtractor::extractOpenGraphTitle() gibt nicht mehr pageTitle zurück
Wieso wird bei der extractOpenGraphTitle() **$fallback**->pageTitle verwendet, wärend in der extractTwitterTitle() **$reference**->pageTitle verwendet wird?

### PR DESCRIPTION
**Pull request by bildschirmartist**
Added missing page social tags fix for extractOpenGraphTitle Method. Fixes #28.

### CODE REVIEW

**Comment by bildschirmartist** [comment]
Hi @dmolineus ,
is there any chance that you could take a look at my PR at short notice? Alternatively, I would look for another solution that works for me. 
Many thanks in advance and best regards

**Comment by bildschirmartist** [comment]
> Hi @dmolineus , is there any chance that you could take a look at my PR at short notice? Alternatively, I would look for another solution that works for me. Many thanks in advance and best regards

Anyone?

**Comment by frontendschlampe** [comment]
please have a little patience … we'll check it asap. … thank you

**Comment by dmolineus** [comment]
> is there any chance that you could take a look at my PR at short notice? Alternatively, I would look for another solution that works for me.

Thanks @bildschirmartist. You're always able to use your patched fork until a bugfix is released.

**Pull request merged**
